### ISSUE TITLE
does not bind in component angular 4

### ISSUE THREAD

**Issue by lfaguiar** [amarkes/brmasker4#2]
The mask is worked but the value do not go to component in angular 4, my html is:

`<input id="id_cpf" name="nome_cpf" type="text" [(ngModel)]="value_cpf" class="form-control" placeholder="Informe o nome" title="Informe o nome" [readonly]="!true" maxlength="" [required]="" placeholder="CPF" [brmasker]="{mask:'000.000.000-00'}"/>`

**Comment by bbfdev** [comment]
The mask is worked but the value do not go to component in angular 4:

`<input type="text" name="cpfCnpj" autocomplete="off" onpaste="return false" ondrop="return false" formControlName="cpfCnpj"
              placeholder="{{globalMessage.input.placeholder}}" [brmasker]="{person: true}" (input)="catchEntry(rForm.controls['cpfCnpj'].value)">`

**Comment by amarkes** [comment]
[like](https://github.com/amarkes/br-masker-ionic-3)

**Comment by amarkes** [comment]
# Lib is deprecated 

We're sorry, but we'll focus only on one [library](https://github.com/amarkes/br-masker-ionic-3)
