### ISSUE TITLE
moneyMask

### ISSUE THREAD

**Issue by wesleyxavier** [amarkes/brmasker4#3]
tmp = tmp.replace(re, '.$1');
 if (new RegExp(/^[\.][\d]{2}$/g).test(tmp)) tmp = '0'+tmp;
 if (new RegExp(/^0[\d]{1}[\.]{1}[\d]{2}$/g).test(tmp)) tmp = tmp.substr(1);
return tmp;

Adicionei este código na biblioteca pessoal para melhorar o resultado da moneyMask.
Poderia ser nativo algo como isto, pois quando dou update preciso recolocar esse adicional.

**Comment by amarkes** [comment]
pode colocar sim, so fazer pull.
coloca como uma outra mascara que nao seja a já existente, assim não quebra ninguém.

**Comment by amarkes** [comment]
# Lib is deprecated 

We're sorry, but we'll focus only on one [library](https://github.com/amarkes/br-masker-ionic-3)
